In [52]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression , ElasticNet 
from sklearn.decomposition import PCA
from sklearn.metrics import r2_score
import pandas as pd
import numpy as np

data = fetch_california_housing()

X = data.data
y = data.target
print(X)
print(y)
feature_name = data.feature_names
print(feature_name)
X.shape
print(X.shape)
data

df = pd.DataFrame(X , columns= feature_name)
df["MedHouseVal"] = y

#series or df--concat , list---data 

df


[[   8.3252       41.            6.98412698 ...    2.55555556
    37.88       -122.23      ]
 [   8.3014       21.            6.23813708 ...    2.10984183
    37.86       -122.22      ]
 [   7.2574       52.            8.28813559 ...    2.80225989
    37.85       -122.24      ]
 ...
 [   1.7          17.            5.20554273 ...    2.3256351
    39.43       -121.22      ]
 [   1.8672       18.            5.32951289 ...    2.12320917
    39.43       -121.32      ]
 [   2.3886       16.            5.25471698 ...    2.61698113
    39.37       -121.24      ]]
[4.526 3.585 3.521 ... 0.923 0.847 0.894]
['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
(20640, 8)


MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  MedHouseVal  
0        -122.23        4.526  
1        -122.22        3.585  
2        -122.24        3.521  
3        -122.25        3.413  
4        -122.25        3.422  
...          ...          ...  
20635    -121.09        0.781  
20636    -121.21        0.771  
20637    -121.22        0.923  
20638    -121.32        0.847  
20639    -121.24        0.894  

[20640 rows x 9 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.2 , random_state= 42)
Scaled = StandardScaler()
Scaled.fit(X_train)
X_train_scaled = Scaled.transform(X_train)
X_test_scaled = Scaled.transform(X_test)
X_train , X_train_scaled

#fit(normalization) just train for rule
#do not scale target(y doesnt need to be normalized)
#fit --- sensitive to scale of feature
# transform to scale it without see test 


(array([[   3.2596    ,   33.        ,    5.0176565 , ...,    3.6918138 ,
           32.71      , -117.03      ],
        [   3.8125    ,   49.        ,    4.47354497, ...,    1.73809524,
           33.77      , -118.16      ],
        [   4.1563    ,    4.        ,    5.64583333, ...,    2.72321429,
           34.66      , -120.48      ],
        ...,
        [   2.9344    ,   36.        ,    3.98671727, ...,    3.33206831,
           34.03      , -118.38      ],
        [   5.7192    ,   15.        ,    6.39534884, ...,    3.17889088,
           37.58      , -121.96      ],
        [   2.5755    ,   52.        ,    3.40257649, ...,    2.10869565,
           37.77      , -122.42      ]]),
 array([[-0.326196  ,  0.34849025, -0.17491646, ...,  0.05137609,
         -1.3728112 ,  1.27258656],
        [-0.03584338,  1.61811813, -0.40283542, ..., -0.11736222,
         -0.87669601,  0.70916212],
        [ 0.14470145, -1.95271028,  0.08821601, ..., -0.03227969,
         -0.46014647, -0.447603

In [54]:
lin_model = LinearRegression()
lin_model.fit(X_train_scaled, y_train)
y_test_pred = lin_model.predict(X_test_scaled)
y_train_pred = lin_model.predict(X_train_scaled)
r2_test =r2_score(y_test , y_test_pred)
r2_train = r2_score(y_train , y_train_pred)

overfitting_lin =r2_train - r2_test
r2_train, r2_test, overfitting_lin


(0.6125511913966952, 0.575787706032451, 0.03676348536424423)

In [55]:
m = lin_model.coef_
df_m = pd.DataFrame(m , index=feature_name , columns= ["coef_lin"])
df_m.sort_values(by = "coef_lin" , ascending=False)

# b = lin_model.intercept_
# b



coef_lin
MedInc      0.854383
AveBedrms   0.339259
HouseAge    0.122546
Population -0.002308
AveOccup   -0.040829
AveRooms   -0.294410
Longitude  -0.869842
Latitude   -0.896929

In [56]:
elastic_model =ElasticNet(alpha=0.1 , l1_ratio=0.5)

elastic_model.fit(X_train_scaled, y_train)

y_train_pred_elas = elastic_model.predict(X_train_scaled)
r2_train_elas = r2_score(y_train, y_train_pred_elas)
y_test_pred_elas = elastic_model.predict(X_test_scaled)
r2_test_elas= r2_score(y_test , y_test_pred_elas)

overfitting_elastic =r2_train_elas - r2_test_elas
r2_train_elas, r2_test_elas, overfitting_elastic 

(0.5307617190050341, 0.5147647043408882, 0.015997014664145937)

In [57]:
mel = elastic_model.coef_
df_e = pd.DataFrame(mel , index=feature_name , columns= ["coef_elas"])
df_e.sort_values(by = "coef_elas" , ascending=False)

coef_elas
MedInc       0.713818
HouseAge     0.137288
AveRooms    -0.000000
AveBedrms    0.000000
Population   0.000000
AveOccup    -0.000000
Longitude   -0.133250
Latitude    -0.175737

In [58]:
diff_df=pd.concat([df_m , df_e] , axis=1)
diff_df.columns = ["coef_lin", "coef_elas"]
diff_df["diff"] = diff_df["coef_lin"] - diff_df["coef_elas"]

diff_df

coef_lin  coef_elas      diff
MedInc      0.854383   0.713818  0.140565
HouseAge    0.122546   0.137288 -0.014742
AveRooms   -0.294410  -0.000000 -0.294410
AveBedrms   0.339259   0.000000  0.339259
Population -0.002308   0.000000 -0.002308
AveOccup   -0.040829  -0.000000 -0.040829
Latitude   -0.896929  -0.175737 -0.721192
Longitude  -0.869842  -0.133250 -0.736592

In [59]:
pca =PCA(n_components=5)
X_pca_train = pca.fit_transform(X_train_scaled)
X_pca_test=pca.transform(X_test_scaled)


In [60]:
lin_pca_model = LinearRegression().fit(X_pca_train, y_train)
y_pca_test = lin_pca_model.predict(X_pca_test)
y_pca_train = lin_pca_model.predict(X_pca_train)
r2_train_pca=r2_score(y_train, y_pca_train)
r2_test_pca= r2_score(y_test, y_pca_test)
overfitting_pca= r2_train_pca - r2_test_pca
r2_train_pca, r2_test_pca, overfitting_pca




(0.45672908210341057, 0.4329231707013418, 0.02380591140206878)

In [63]:
result = [[r2_train, r2_test, overfitting_lin],
        [r2_train_elas, r2_test_elas, overfitting_elastic],
        [r2_train_pca, r2_test_pca, overfitting_pca]]


ovrfitting = pd.DataFrame(result ,index= ["lin_model", "elasticnet", "pca"], columns= ["r2_score_train","r2_score_test","overfitting"])

ovrfitting

r2_score_train  r2_score_test  overfitting
lin_model         0.612551       0.575788     0.036763
elasticnet        0.530762       0.514765     0.015997
pca               0.456729       0.432923     0.023806